Learning-Fuze/c11_doubledate

development_blog.html
login_handler.php
login_service.js
proto_login_controller.js
proto_login_page.html
proto_login_script.js

Still using hard-coded data in the back end login_handler.php; not connected to database yet.

Basic login prototype and service complete.

---

.gitignore
README.md
proto_user_controller.js
proto_user_page.html
user/add.php
user/check_status.php
user/connect_database.php.config
user/login.php
user/user_common.php
user_service.js

Changed user service to use database.
Added functionality to add a user to the user database.
See me for a copy of the sample user database; I did not put this into GitHub.

Modified user service to use database; now can add users.

---

routing.js

Dan's change to the routing for the welcome page

---

home.html
pages/interests_home.html
pages/sign_up.html
pages/user_age_range.html
pages/user_location.html
style.css

Added more at-home activities and replaced previous placeholders for those buttons

added at home interests

---

pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html

Added/deleted user interests after group collab

finalize user interests

---

README.md
profile/profile_common.php
profile_service.js
proto_profile_page.html
tables/profiles.sql

Renamed foreignTravel to travelAbroad.
Added interests for crafts, bookClub, and movieNight.
Fixed up README.md formatting.

Final interests list.

---

dansFolder/index.html
dansFolder/protoTypeRouting.js
dansFolder/proto_page_3.html
pages/interests_home.html
routing.js
style.css
user/connect_database.php

added a service for the night in view and functionality for the controller, still needs work,

'interestfunctionality'

---

home.html
pages/age_range.html
pages/sign_up.html
routing.js

planning to delete range sliders per group collab with eric

range sliders planning to delete

---

pages/age_range.html
pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
pages/location.html
pages/user_age_range.html
routing.js
style.css

-decided to use buttons instead of sliders; deleted slider prototypes;
-styled buttons to make them bigger

deleted sliders and styled buttons

---

pages/interests_home.html

changed the case of what the in home controller is referred too

changed the case of what the in home controller is referred too

---

pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
routing.js

Added ng click and ng class to all interest pages.  
Added arrays to the service. 
Added functions to each interest page's controller.
Added service to each interest page's controllers.
Added controllerAs to each route.

Dan interests v2

---

pages/user_location.html
routing.js

added logic for max 5 characters in zip code input

fixed input for zip code

---

profile/upload.php
proto_profile_controller.js
proto_profile_page.html

- Added check on the back end that some user is logged in; nothing more specific than that.
- Added uploadStatus in the prototype controller to display success or error message from upload.
- Added random image file naming on the back end based on sha1_file(image).
- Added resizing of image file to best fit of 600x450.

Added upload login check, image resizing, random naming.

---

profile/add.php
profile/update.php
profile_service.js

User fills in profile, but add/update translates these to city, latitude, and longitude and stores them in the profile.  Modified add.php, update.php, and prototype controller to return these extra values and make sure they get updated in the display.

Fixed extra zip code fields on profile add/update.

---

profile/get.php
profile/sample_matches.php
profile_service.js
proto_profile_controller.js
proto_profile_page.html

Interim checkin to provide setter methods for profile service.
Sample matches is only half-done; don't try to use it.

Added setter methods to profile service; half-done with sample matches.

---

profile/add.php
profile/profile_common.php
profile/sample_matches.php
profile/update.php
profile_service.js
proto_profile_controller.js
proto_profile_page.html
tables/profiles.sql

Finished sample matches code; returns limit of 20.
Cleanup up "zip_code" to "zipcode" to be more consistent in code.
Fixed handling of quotes in the paragraph: encoded on the storage, and decoded when returned.

Sample matches

---

pages/distance.html
pages/user_location.html
profile_service.js
routing.js
style.css

-check if there is already distance data in profileService
-add logic to keep button highlighted if distance data in profileService

add logic to check and pass distance info to profileService

---

pages/distance.html
pages/user_age_range.html
profile_service.js
routing.js

- add functionality and logic code to pass info to profileService
- store info in service
- added temp 'max' value for 61+ button as 100

add logic to pass info to profileService

---

pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
profile_service.js
routing.js

Adding my changes... changed all of the interest pages and their corresponding controllers

Finished the interests pages

---

home.html
pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
profile_service.js
routing.js

changed interest validation, completed on the home view.

Interest validation

---

pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
routing.js

completed at home interests, a night out interests, outdoors interest

Interest validation 2

---

README.md
match/approve.php
match/calculate.php
match/get.php
match_service.js
profile_service.js
proto_match_controller.js
proto_match_page.html
proto_match_script.js
proto_profile_controller.js
proto_profile_page.html

- Added proto_match_page.html and proto_match_controller.js to test functionality.
- Added match_service.js to interface to back end.
- Added match/calculate.php to handle calculate() operation to fill in the matches table.
- Added match/get.php to get the top 20 matches from the matches table.
- Added match/approve.php to handle approving or rejecting a potential match.
Everything is working on the back end, except for generating e-mails based on a double match.

Match functionality on back end.

---

pages/interests_travel.html
routing.js

add validation and total count functionality to the travel interests page

Finished the travel interests page

---

pages/distance.html
pages/our_age_range.html
pages/our_location.html
pages/signup_email.html
pages/signup_paragraph.html
pages/signup_password.html
pages/their_age_range.html
pages/welcome.html
routing.js
style.css

-added logic for invalid email on initial email page
-worked on initial distance and zip code pages	
-updated initial our age and their age pages to disable next button if user has not selected one

Signup email

---

pages/faq.html
pages/interests_travel.html
routing.js
style.css

Added the FAQ's and Angularized them, the branch name was misnamed, apologies for any confusion

Added the FAQ's and Angularized them

---

pages/signup_email.html
pages/signup_password.html
routing.js
style.css

-added validation for Sign-up Password Page; checks if password and confirm password match, and checks if password meets requirements for security
-added route for Sign-up Paragraph Page

Sign-up password

---

pages/signup_email.html
pages/signup_password.html
style.css

-added button functionality (validation) and styling on email and password sign-up pages

added button functionality

---

pages/before_sample_match.html
pages/sample_match.html
profile/sample_matches.php
profile_service.js
routing.js
style.css

For now, all pages are displayed in a row to scroll.  We can go back and change the handling later if desired.

Added sample matches page handling.

---

home.html
pages/signup_email.html
pages/signup_password.html
routing.js
user_service.js

-add info sending to userService on both submit button on both sign up email and pw page

Add validation on next button

---

pages/match.html
profile_service.js
proto_match_controller.js
routing.js

Added match page, plus approve / reject handling on the back end.

Basic matching and approving/rejecting is now working.

---

pages/signup_paragraph.html
pages/signup_picture.html
routing.js

I only just started the page, but I had fixed a couple of issues I found, mainly the before sample page missing

started the picture page

---

pages/signup_paragraph.html
pages/signup_picture.html
pages/terms.html
profile_service.js
routing.js

Terms and pic pages, routing, and controllers have been added, work in progress
just doing more pull requests to reduce possibility of major merge conflicts

Terms and Conditions and Picture pages

---

pages/terms.html
profile_service.js
routing.js

Finished the basic functionality of the terms page.
need to add a function call to get matches to the submit button
and
needs to be styled
Currently, I'm just trying to get the basic functionality done

terms page

---

home.html
pages/signup_picture.html
routing.js

I added the basic functionality to the signup_picture page
but I basically, copied and pasted Wade's code from his prototype,
and added the drop zone script to the home.html page
I still need to add validation to the page,
and styling, but this may have to wait until Monday as I need a little help since my environment is not set up to make calls to the db.  
I'll go through previous notes to see if I can get that set up.

Almost Finished pic page

---

.gitignore
common/dd_error_log.php
match/approve.php
match/calculate.php
match/get.php
profile/add.php
profile/update.php
proto_user_page.html
tables/users.sql
user/add.php
user/login.php
user/logout.php
user/user_common.php

- Added error logging to logs/doubledateoc_error.log
- Added failedLogins column to users table.
- Added lockReason enum value "failedlogins" at 10 failures.
- Added time delay of repeated failed logins.

Added basic error logging, and failed logins check.

---

pages/interests_travel.html
pages/signup_paragraph.html
pages/terms.html
style.css

Some styling added to the paragraph and terms page
deleted the faq link from the travel interests page
changed the button on the travel interests page and the terms page
took off the data binding from the text area to a paragraph on the paragraph page-- users text will not display outside the textarea
Still working on some of these pages, but just want to get some fixes checked in

Still on pic page

---

pages/interests_travel.html
pages/terms.html
routing.js
style.css

Styled the terms page a little more, 
styled the paragraph page a little more, 
deleted an extra button from the travel_interests page, 
styled the faq page a little

Terms, Paragraph, Travel, FAQ changes

---

home.html
pages/distance.html
style.css

-Added question mark in corner to header
-Added FAQ content into modal

Added FAQ Modal

---

pages/signup_picture.html
routing.js

Added $scope to dependencies, and added explicit variable for data binding.

Fixed picture display on page.

---

pages/our_location.html

This is on MeisterTask as a possible future enhancement.

Comment out 'use our location' button for now.

---

pages/signup_name.html
pages/user_summary.html
routing.js
user_service.js

The basic sign up name page has been created and is working, 
the basic user_summary page is created and works for displaying a name
... some styling may be needed on both pages, as well as validation
the user_summary page currently goes nowhere.. need to add that funcationality

User Summary page and Signup Name page

---

home.html
pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
pages/sample_match.html
pages/signup_email.html
pages/signup_paragraph.html
pages/signup_password.html
pages/user_fyi.html
style.css

-cleaned up interests pages
-restyled subtext and buttons (changed fonts etc)
-re-did layout and context of user paragraph

cleaned up interests pages and re-styled

---

pages/their_age_range.html
routing.js

Still need to add a message telling the user they can select multiple ranges.

Added ability to select multiple 'their age' ranges.

---

home.html
user_input_paragraph.html

-added logic to display characters left in the sign up paragraph 
-finished styling for sign up paragraph page

User paragraph

---

pages/user_summary.html
profile/sample_matches.php
profile_service.js
routing.js
user_service.js

- Fixed flow of signup name.
- Added error div in user summary page.
- Changed max age 99 to 100.

Bug fix 1 - Get add user / add profile working.

---

pages/signup_picture.html
pages/terms.html
pages/user_summary.html
style.css

-styled terms & conditions page (changed font, borders, button)

cleaned up terms and conditions page

---

pages/interests_home.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
pages/signup_name.html
pages/terms.html
proto_edit_profile_sean.html

Took the $log out of the html pages

Cleanup HTML

---

common/dd_error_log.php
match/approve.php
match/calculate.php
match/get.php
profile/add.php
profile/get.php
profile/profile_common.php
profile/sample_matches.php
profile/update.php
user/add.php
user/login.php
user/user_common.php

Also fixed date/time format on dd_error_log; was printing minutes incorrectly.

Added logging of the query string for failed MySQL queries.

---

index.html
style.css

-added title to index.html
-added email us for technical issues section to faq modal
-changed styling for faq modal (font size and sub paragraph color)

Contact us

---

pages/distance.html
pages/signup_email.html
pages/signup_name.html
pages/signup_paragraph.html
pages/signup_password.html
pages/terms.html
pages/their_age_range.html

Changed the aria label on all html pages being used, except index(will get to that next), 
deleted some commented out html,
a couple of views had an opening anchor tag commented out, but not the ending tag, so I deleted those

Aria Labels

---

index.html

-added href tag so that bootstrap modal correctly functions on mobile

fixed faq modal on mobile

---

pages/interests_travel.html

removed the text asking for the user to select at least one travel interest
took off the ng-disable which disabled the button if they did not choose any interests
Fixed the aria labels

No travel interest

---

index.html
pages/terms.html

-commented out irrelevant faq sections
-added a href tags to e-mails mentioned in the terms & conditions page

cleaned up faq and terms pages

---

pages/user_summary.html
routing.js
user_service.js

Also cleaned up some console logs to not display the password.

Give better message for bad zipcode affecting profile add.

---

pages/signup_paragraph.html
pages/their_age_range.html
pages/welcome.html
routing.js

-changed welcome buttons noting 'we've been here' vs 'i've been here'
-cleaned up bug indicating number of characters left to go to 0, instead of stopping at 31
-added 'select one or more' on their_age_range page

Welcome buttons, Age Range Page, and sign up paragraph

---

pages/terms.html

run on sentence fixed
elements added to an un-ordered list

terms and conditions

---

pages/match.html
pages/signup_name.html
pages/signup_picture.html
style.css

added button to picture page, added overflow property to match card, 
added max-height and max width to theh thumb images

Picture page, match card, thumbs

---

pages/match.html
style.css

fixed the thumbs up and down issue
added some padding to the paragraphs on the match page

Match page

---

pages/edit_profile.html
pages/edit_profile_2.html
pages/interests_out.html
pages/interests_outdoors.html
pages/interests_travel.html
routing.js
style.css

edit profile page added
travel interests
outdoor interests
night out interests

edit profile page

---

style.css

It was affecting the Terms and Conditions ul and li tags.

Make wine glass styling specific to only wine glass animation.
